-- MySQL Script generated by MySQL Workbench
-- 08/27/15 20:43:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `setor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `setor` ;

CREATE TABLE IF NOT EXISTS `setor` (
  `idsetor` INT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idsetor`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargo` ;

CREATE TABLE IF NOT EXISTS `cargo` (
  `idcargo` INT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `setor_idsetor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcargo`, `setor_idsetor`)  COMMENT '',
  INDEX `fk_cargo_setor1_idx` (`setor_idsetor` ASC)  COMMENT '',
  CONSTRAINT `fk_cargo_setor1`
    FOREIGN KEY (`setor_idsetor`)
    REFERENCES `setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `senha` VARCHAR(45) NULL COMMENT '',
  `login` VARCHAR(45) NULL COMMENT '',
  `cargo_idcargo` INT NOT NULL COMMENT '',
  `cargo_setor_idsetor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idusuario`, `cargo_idcargo`, `cargo_setor_idsetor`)  COMMENT '',
  INDEX `fk_usuario_cargo1_idx` (`cargo_idcargo` ASC, `cargo_setor_idsetor` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_cargo1`
    FOREIGN KEY (`cargo_idcargo` , `cargo_setor_idsetor`)
    REFERENCES `cargo` (`idcargo` , `setor_idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `local` ;

CREATE TABLE IF NOT EXISTS `local` (
  `idlocal` INT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idlocal`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedido` ;

CREATE TABLE IF NOT EXISTS `pedido` (
  `idpedido` INT NULL AUTO_INCREMENT COMMENT '',
  `datahora` DATE NULL COMMENT '',
  `descricao` VARCHAR(999) NULL COMMENT '',
  `situacao` INT NULL COMMENT '',
  `usuario_idusuario` INT NOT NULL COMMENT '',
  `local_idlocal` INT NOT NULL COMMENT '',
  `setor_idsetor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idpedido`, `usuario_idusuario`, `local_idlocal`)  COMMENT '',
  INDEX `fk_pedido_usuario_idx` (`usuario_idusuario` ASC)  COMMENT '',
  INDEX `fk_pedido_local1_idx` (`local_idlocal` ASC)  COMMENT '',
  INDEX `fk_pedido_setor1_idx` (`setor_idsetor` ASC)  COMMENT '',
  CONSTRAINT `fk_pedido_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_local1`
    FOREIGN KEY (`local_idlocal`)
    REFERENCES `local` (`idlocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_setor1`
    FOREIGN KEY (`setor_idsetor`)
    REFERENCES `setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
